---
title: "Experiment 2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
```{r setup}
library(tidyverse)
library(readxl)
theme_set(theme_classic())

se <- function(x, n) {
  sd(x)/sqrt(n)
}
```

## Data Wrangling
```{r data}
data <- read_csv("exp2data.csv") %>% 
  filter(usable == 1 & english_all_or_most_or_first_lang_or_school == 1 & age < 9) %>% 
  mutate(multiSSexperience = number_of_SS_in_home > 1,
         high_tom_no_why = ifelse(tom_no_why > 4, 1, 0),
         high_tom = ifelse(tom_no_moral > 6, 1, 0),
         chose_song_1 = ifelse(first_song == test_q, 1, 0),
         chose_correctly = ifelse(condition == "VUI", ifelse(chose_song_1, 0, 1), ifelse(chose_song_1, 1, 0)),
         fb_score = (rachel_prediction_implicit_false_belief + diana_prediction_false_belief_location + allie_predicition_false_belief_location)/3.0)
data$condition <- recode(data$condition, "VUI"="AI")
data$condition <- factor(data$condition, levels = c("Person", "AI"))
data$multiSSexperience <- factor(data$multiSSexperience)
```

## Demographics
```{r data}
mean(data$age)
sd(data$age)

data %>% group_by(gender) %>% summarise(n = n())
data %>% group_by(number_of_SS_in_home) %>% summarise(n = n())
```

## GLM
```{r data}
mod <- glm(chose_song_1  ~ 1 + condition * age * multiSSexperience, data=data, family = binomial)
summary(mod)

mod <- lm(tom  ~ age, data=data)
summary(mod)
person_data <- data %>%  filter(condition == "Person")
cor.test(person_data$fb_score, person_data$age, method = "spearman")
summary(glm(chose_song_1  ~ fb_score, data=person_data, family = binomial))

mod2 <- glm(chose_song_1  ~ age * multiSSexperience, data=data %>% filter(condition=="AI"), family = binomial)
summary(mod2)
```

## Plot Age Scatter
```{r data}
hypothesis_data <- data.frame(age=rep(c(3,5,8.5), times=4),
                 condition=rep(c('Person', 'AI'), each=6),
                 multiSSexperience=rep(c('False', 'False', 'False', 'True', 'True', 'True'), times=2),
                 chose_song_1=c(0.25, 0.85, 0.9, 0.27, 0.87, 0.92, 0.3, 0.84, 0.89, 0.26, 0.8, 0.5))
hypothesis_data$condition <- factor(hypothesis_data$condition, levels = c("Person", "AI")) 

ggplot(data, aes(x=age, y=chose_song_1)) +
  # geom_line(aes(color=condition, linetype=multiSSexperience)) +
  geom_smooth(method = "glm", method.args=list(family="binomial"),
    se = FALSE, aes(color=condition)) +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_linetype_manual(name = "Has Connected Smart\nSpeakers at Home", values = c(1,3), labels = c("False", "True")) +
  scale_color_manual(values=c("#B6B6B6", "#457AEE")) +
  labs(title = "Hypotheses",
       x = "Age",
       y = "Percent Consistent w/ Separate Minds",
       color = "Condition") +
  guides(color = guide_legend(order = 1), 
        linetype = guide_legend(order = 2)) +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "right",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))

adult_data <- data.frame(age=c(10,10),
                 condition=c('Person', 'AI'),
                 multiSSexperience=c('False', 'False'),
                 chose_song_1=c(0.73,0.12))
adult_data$condition <- factor(adult_data$condition, levels = c("Person", "AI"))

ggplot(data, aes(x=age, y=chose_song_1)) +
    geom_point(data=adult_data, aes(color=condition, size = 1.5)) +
    geom_point(aes(color=condition, shape=multiSSexperience), position=position_jitter(width = 0.02, height = 0.04)) +
  # geom_smooth(method = "glm", method.args=list(family="binomial"), se = FALSE, aes(color=condition, linetype=multiSSexperience)) +
  geom_smooth(se = FALSE, aes(color=condition, linetype=multiSSexperience)) +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1), labels=c(0,20,40,60,80,100)) +
  scale_x_continuous(limits=c(3,10),breaks=c(3,4,5,6,7,8,10),labels = c(3,4,5,6,7,8,"Adults")) +
  scale_linetype_manual(name = ">1 SS", values = c(1,3), labels = c("False", "True")) +
  scale_color_manual(values=c("#B6B6B6", "#457AEE")) +
  labs(title = "Experiment 2 Data",
       x = "Age",
       y = "Percent Predicting Paisia Plays Song 1",
       color = "Condition",
       shape = ">1 SS") +
  guides(color = guide_legend(order = 1), 
        linetype = guide_legend(order = 2)) +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "right",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold")) +
        scale_size(guide="none")
```

## Older Kids
```{r older}
ggplot(data %>% filter(age >= 9), aes(x=age, y=chose_song_1)) +
  geom_smooth(method = "glm", method.args=list(family="binomial"), se = FALSE, aes(color=condition, linetype=multiSSexperience)) +
  geom_point(data=adult_data, aes(color=condition, size = 1.5)) +
  geom_point(aes(color=condition, shape=multiSSexperience), position=position_jitter(width = 0.02, height = 0.04)) +
  scale_y_continuous(limits=c(-0.1,1.1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_x_continuous(limits=c(9,14),breaks=c(9,10,11,12,14),labels = c(9,10,11,12,"Adults")) +
  scale_linetype_manual(name = "Multi SS Experience", values = c(1,3), labels = c("False", "True")) +
  scale_color_manual(values=c("#B6B6B6", "#457AEE")) +
  guides(size = FALSE) +
  labs(title = "Older Children Pilot Data",
       x = "Age",
       y = "Percent Consistent w/ Separate Minds",
       color = "Condition") +
  guides(color = guide_legend(order = 1), 
        linetype = guide_legend(order = 2)) +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "right",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))

older_plot_data <- data %>% 
  filter(age >= 9 & condition == "AI") %>% 
  group_by(floor_age, condition, multiSSexperience) %>% 
  summarise(percent = mean(chose_song_1),
            n = paste("N =", n()),
            m_age = round(mean(age),2),
            label = paste(n, "\n", m_age))

ggplot(older_plot_data, aes(fill=multiSSexperience, x=floor_age, y=percent)) +
  geom_col(position="dodge") +
  geom_text(aes(label=label), position = position_dodge(width = .9))
```

```{r, warning=FALSE, message = FALSE}
require(gridExtra)
theme_set(theme_classic())

colors <- c("Has Connected Smart Speakers" = "blue", "Without Connected Smart Speakers" = "red", "False Belief Score" = "black")


person_plot <- ggplot() +
    geom_smooth(data = data %>% filter(condition=="Person")  %>% filter(number_of_SS_in_home > 1), aes(x=age, y=chose_song_1), color="red") +
  geom_smooth(data = data %>% filter(condition=="Person")  %>% filter(number_of_SS_in_home <= 1), aes(x=age, y=chose_song_1), color="blue") +
  geom_smooth(data = data %>% filter(condition=="Person"), aes(x=age, y=fb_score), color="black") +
  coord_cartesian(ylim = c(0,1)) +
  labs(title = "Person Condition",
       x = "Age",
       y = "Accuracy",
       color = "") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"))

ai_plot <- ggplot() +
  geom_smooth(data = data %>% filter(condition=="AI")  %>% filter(number_of_SS_in_home > 1), aes(x=age, y=chose_song_1, color="Has Connected Smart Speakers")) +
  geom_smooth(data = data %>% filter(condition=="AI") %>% filter(number_of_SS_in_home <= 1), aes(x=age, y=chose_song_1, color="Without Connected Smart Speakers")) +
  geom_smooth(data = data %>% filter(condition=="AI"), aes(x=age, y=fb_score, color="False Belief Score")) +
  coord_cartesian(ylim = c(0,1)) +
  labs(title = "AI Condition",
       x = "Age",
       y = "",
       color = "") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "none",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold")) + 
  scale_color_manual(values = colors)

person_plot
ai_plot

grid.arrange(person_plot, ai_plot, ncol=2)
```

```{r all_tom}
max_fb_only = max(data$tom_fb_only)
max_tom_fb_with_exp_control = max(data$tom_fb_with_exp_control)
max_tom_fb_control = max(data$tom_fb_control)
max_tom_no_why = max(data$tom_no_why)
max_tom_no_moral = max(data$tom_no_moral)
max_tom_no_why_no_moral = max(data$tom_no_why_no_moral)
max_tom = max(data$tom)

tom_data <- data %>% group_by(floor_age) %>% 
  summarise(false_belief_predction = mean(tom_fb_only / max_fb_only),
            controlled_false_belief = mean(tom_fb_control / max_tom_fb_control),
            false_belief_all = mean(tom_fb_with_exp_control / max_tom_fb_with_exp_control)) %>% 
            # no_explanations = mean(tom_no_why / max_tom_no_why),
            # no_moral = mean(tom_no_moral / max_tom_no_moral),
            # no_explanations_no_moral = mean(tom_no_why_no_moral / max_tom_no_why_no_moral),
            # all = mean(tom / max_tom)) %>% 
  gather(scoring, mean, -floor_age)


ggplot(tom_data, aes(x=floor_age, y=mean, color=scoring)) +
  geom_line()
  
```


```{r by_child_tom}
max_fb_only = max(data$tom_fb_only)
max_tom_fb_with_exp_control = max(data$tom_fb_with_exp_control)
max_tom_no_why = max(data$tom_no_why)
max_tom_no_moral = max(data$tom_no_moral)
max_tom_no_why_no_moral = max(data$tom_no_why_no_moral)
max_tom = max(data$tom)

child_tom_data <- data %>%
  mutate(false_belief_predction = tom_fb_only / max_fb_only,
         false_belief_all = tom_fb_with_exp_control / max_tom_fb_with_exp_control,
         no_explanations = tom_no_why / max_tom_no_why,
         no_moral = tom_no_moral / max_tom_no_moral,
         no_explanations_no_moral = tom_no_why_no_moral / max_tom_no_why_no_moral,
         all = tom / max_tom)


ggplot(tom_data, aes(x=floor_age, y=mean, color=scoring)) +
  geom_line()
  
```

## TEST: Quadratic Term
```{r data}
data$age2 <- data$age^2
mod <- lm(chose_song_1  ~ condition * age2, data=data, family = binomial)
summary(mod)
mod <- lm(chose_song_1  ~ condition * I(age^2), data=data, family = binomial)
summary(mod)
```

```{r 2024-addition}
bar_data <- data %>% 
  group_by(floor_age, condition) %>% 
  summarise(percent_song_1 = mean(chose_song_1),
            n = n())

ggplot(data, aes(x=floor_age, y=chose_song_1)) +
  geom_col(data=bar_data, aes(x=floor_age, y=percent_song_1, fill=condition), position="Dodge", alpha=0.3) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), formula = y ~ x + I(x^2), aes(color=condition), se=FALSE) +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_fill_manual(values=c("#888888", "#457AEE")) +
  scale_color_manual(values=c("#888888", "#457AEE")) +
  labs(title = "Developmental Data",
       x = "Age",
       y = "Percent Consistent w/ Separate Minds",
       color = "Condition") +
  guides(color = guide_legend(order = 1), 
        linetype = guide_legend(order = 2)) +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "right",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))
```
