---
title: "Experiment 1"
output: html_document
---

## Setup
```{r setup}
library(tidyverse)
library(readxl)

se <- function(x, n) {
  sd(x)/sqrt(n)
}
```

## Data Wrangling
```{r data}
data <- read_csv("Experiment1_data.csv")%>% 
  mutate(chose_song1 = (song1 == answer))

```

## Demographics - Gender

```{r}
data_gender <- data %>% 
  count(gender)

data_gender
```

## Descriptive stats - Age Range

```{r}
age_range <- data %>% 
  arrange(age) %>% 
  slice(1, 57) %>% 
  select(age)

age_range

```

## Summary statistics

```{r}
plot_data <- data %>% 
  group_by(condition) %>% 
  summarise(percent = mean(chose_song1),
            n = n(),
            se = se(chose_song1,n),
            ci = 1.96*(sd(chose_song1)/sqrt(n())),
            ci_min = max(0, percent - ci),
            ci_max = min(1,percent + ci))

plot_data
```

## GLM
```{r glm}
mod <- glm(chose_song1 ~ condition, family = binomial, data)
summary(mod)

allEffects(mod)

library(effects)
```

## Binomial Tests
```{r glm}
person_data <- data %>% 
  filter(condition == "Person") %>% 
  summarise(x = sum(chose_song1),
            n = n())
binom.test(x = person_data$x, n = person_data$n, alternative = "greater")

ai_data <- data %>% 
  filter(condition == "AI") %>% 
  summarise(x = sum(chose_song1),
            n = n())
binom.test(x = ai_data$x, n = ai_data$n, alternative = "less")
```

## Plot
```{r plot}
plot_data <- data %>% 
  group_by(condition) %>% 
  summarise(percent = mean(chose_song1),
            n = n(),
            se = se(chose_song1,n),
            ci = 1.96*(sd(chose_song1)/sqrt(n())),
            ci_min = max(0, percent - ci),
            ci_max = min(1,percent + ci)) %>% 
  mutate(percent = percent * 100,
         ci_min = ci_min * 100,
         ci_max = ci_max * 100)
  
plot_data$condition <- factor(plot_data$condition, levels = c("Person", "AI"))


ggplot(plot_data, aes(fill=condition, x=condition, y=percent)) +
  geom_col() + 
  geom_errorbar(aes(ymin = ci_min, ymax = ci_max), width=0.3, position = position_dodge(0.9)) +
  ylab("Percent Choosing Song 1") +
  xlab("") +
  labs(title = "Adult Predictions of Song Played",
       x = "",
       y = "Percent Consistent w/ Separate Minds",
       fill = "Condition") +
  scale_fill_manual(values=c("#999999", "#3D2785")) +
  scale_y_continuous(limit = c(0,100), breaks=c(0,25,50,75,100), labels = c(0, 25, 50, 75, 100)) +
  theme_cowplot() +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 16, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 16, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "right",
        legend.justification = "left",
        legend.text = element_text(size = 16),
        legend.title = element_text(face = "bold"))

ggsave("figures/exp1_purple.png", bg = "white", width = 7, height = 7)
```