---
title: "LookIt Analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
```{r setup}
library(tidyverse)
library(readxl)
library(irr)
theme_set(theme_classic())

se <- function(x, n) {
  sd(x)/sqrt(n)
}
```

## Data Wrangling
```{r data}
data <- read_csv("lookit_data.csv")
data <- data %>% 
  mutate(age = age_days/365.25,
         floor_age = floor(age),
         fb_over_2 = as.integer((rachel_false_belief + diana_false_belief + allie_false_belief)>=2))
         

data$voice_assistant_frequency = factor(data$voice_assistant_frequency, levels = c("Never", "Less than once a week
", "About once a week", "About once a day", "Several times a day"))
data <- data %>% mutate(va_daily = (voice_assistant_frequency == "About once a day" | voice_assistant_frequency == "Several times a day"))
data <- data %>% mutate(ss_daily = (smart_speaker_frequency == "About once a day" | smart_speaker_frequency == "Several times a day"))
data <- data %>% mutate(multiSSexperience = (num_speakers >= 2))
```
## Demograpics
```{r demo}
data %>% summarise(
  mean_age = mean(age),
  sd_age = sd(age),
  n = n()
)
```

## H1
```{r h1}
mod <- glm(chose_song_1 ~ 1 + age * condition, family = binomial, data)
summary(mod)
```

## H2
```{r h1}
mod <- glm(chose_song_1 ~ age^2, family = binomial, data %>% filter(condition=="AI"))
summary(mod)
```
## Plot Age
```{r data}
require(gridExtra)
binned_data <- data
binned_data$age_group <- cut(data$age,
                    breaks = c(3, 5, 7, 9, 11, 13, Inf),
                    labels = c("3-4", "5-6", "7-8", "9-10", "11-12", "13+"),
                    right = FALSE)

bar_data <- binned_data %>% 
  group_by(age_group, condition) %>% 
  summarise(percent_song_1 = mean(chose_song_1),
            n = n())

key_plot <- ggplot(binned_data, aes(x=as.numeric(factor(age_group)), y=chose_song_1)) +
  geom_col(data=bar_data, aes(x=age_group, y=percent_song_1, fill=condition), position="Dodge", alpha=0.3) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), formula = y ~ x + I(x^2), aes(color=condition)) +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_fill_manual(values=c("#3D2785", "#999999")) +
  scale_color_manual(values=c("#3D2785", "#999999")) +
  labs(title = "Study Data",
       x = "Age",
       y = "Percent Consistent w/ Separate Minds",
       color = "Condition") +
  guides(color = guide_legend(order = 1), 
        linetype = guide_legend(order = 2),
        fill = "none") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "none",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))

key_plot
fb_bar_data <- binned_data %>% 
  group_by(age_group, condition) %>% 
  summarise(percent_fb_over_2 = mean(fb_over_2),
            n = n())

fb_plot <- ggplot(binned_data, aes(x=as.numeric(factor(age_group)), y=fb_over_2)) +
  geom_col(data=fb_bar_data, aes(x=age_group, y=percent_fb_over_2, fill=condition), position="Dodge", alpha=0.3) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), formula = y ~ x, aes(color=condition)) +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_fill_manual(values=c("#3D2785", "#999999")) +
  scale_color_manual(values=c("#3D2785", "#999999")) +
  labs(title = "False Belief Data",
       x = "Age",
       y = "Percent Above Chance on False Belief",
       color = "Condition") +
  guides(color = guide_legend(order = 1), 
        linetype = guide_legend(order = 2),
        fill = "none") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "none",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))

grid.arrange(key_plot, fb_plot, ncol=2)
```


```{r fb_corr}
person_data <- data %>% 
  filter(condition == "Person")
chisq.test(person_data$fb_over_2, person_data$chose_song_1)

fb_bar_data <- data %>% 
  group_by(floor_age) %>% 
  summarise(mean_fb = mean(fb_score))

ggplot() +
  geom_col(data=fb_bar_data, aes(x=floor_age, y=mean_fb))
  geom_smooth(data=data, aes(x=age, y=fb_score), color="black") +
  coord_cartesian(ylim = c(0,1)) +
  labs(title = "Person Condition",
       x = "Age",
       y = "Accuracy",
       color = "") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"))
```


## Exploratory
```{r exploratory_multiSS}
multiSS_data <- data %>% filter(condition=="AI" & !is.na(multiSSexperience))
mod <- glm(chose_song_1 ~ 1 + age^2 * multiSSexperience, family = binomial, multiSS_data)
summary(mod)



multiSS_data$age_group <- cut(multiSS_data$age,
                    breaks = c(3, 5, 7, 9, 11, 13, Inf),
                    labels = c("3-4", "5-6", "7-8", "9-10", "11-12", "13+"),
                    right = FALSE)

multiSS_data$multiSSexperience[multiSS_data$multiSSexperience == TRUE] <- "2 or more"
multiSS_data$multiSSexperience[multiSS_data$multiSSexperience == FALSE] <- "Less than 2"

multiSS_bar_data <- multiSS_data %>% 
  group_by(age_group, multiSSexperience) %>% 
  summarise(percent_song_1 = mean(chose_song_1),
            n = n())

ggplot(multiSS_data, aes(x=as.numeric(factor(age_group)), y=chose_song_1)) +
  geom_col(data=multiSS_bar_data, aes(x=age_group, y=percent_song_1, fill=multiSSexperience), position="Dodge") +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_fill_manual(values=c("#3D2785", "#B6A6E9")) +
  labs(title = "Impact of Owning Multiple Smart Speakers",
       x = "Age",
       y = "Percent Consistent w/ Separate Minds",
       fill = "Number of Smart\nSeakers in Home") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "right",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))


wide_multiSS <- multiSS_bar_data %>% 
  select(-percent_song_1) %>% 
  pivot_wider(names_from = multiSSexperience, values_from = n)
```

```{r exploratory_dailySS}
exploratory_data <- data %>% filter(condition=="AI" & !is.na(ss_daily))
# exploratory_data <- exploratory_data %>% filter(floor_age >= 6)
mod <- glm(chose_song_1 ~ 1 + age^2 * ss_daily, family = binomial, exploratory_data)
summary(mod)

exploratory_data$age_group <- cut(exploratory_data$age,
                    breaks = c(3, 5, 7, 9, 11, 13, Inf),
                    labels = c("3-4", "5-6", "7-8", "9-10", "11-12", "13+"),
                    right = FALSE)

exploratory_data$ss_daily[exploratory_data$ss_daily == TRUE] <- "Daily"
exploratory_data$ss_daily[exploratory_data$ss_daily == FALSE] <- "Less than Daily"

exploratory_bar_data <- exploratory_data %>% 
  group_by(age_group, ss_daily) %>% 
  summarise(percent_song_1 = mean(chose_song_1),
            n = n())

ggplot(data=exploratory_bar_data, aes(x=age_group, y=percent_song_1, fill=ss_daily)) +
  geom_col(position="Dodge") +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_fill_manual(values=c("#3D2785", "#B6A6E9")) +
  labs(title = "Impact of Daily Smart Speaker Usage",
       x = "Age",
       y = "Percent Consistent w/ Separate Minds",
       fill = "Smart Speaker\nUsage Frequency") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "right",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))


wide_dailySS <- exploratory_bar_data %>% 
  select(-percent_song_1) %>% 
  pivot_wider(names_from = ss_daily, values_from = n)
```
