---
title: "Zoom Pilot Analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
```{r setup}
library(tidyverse)
library(readxl)
theme_set(theme_classic())

se <- function(x, n) {
  sd(x)/sqrt(n)
}
```

## Data Wrangling
```{r data}
data <- read_csv("zoom_data.csv") %>% 
  filter(usable == 1 & english_all_or_most_or_first_lang_or_school == 1 & age < 9) %>% 
  mutate(multiSSexperience = number_of_SS_in_home > 1,
         high_tom_no_why = ifelse(tom_no_why > 4, 1, 0),
         high_tom = ifelse(tom_no_moral > 6, 1, 0),
         chose_song_1 = ifelse(first_song == test_q, 1, 0),
         chose_correctly = ifelse(condition == "VUI", ifelse(chose_song_1, 0, 1), ifelse(chose_song_1, 1, 0)),
         fb_score = (rachel_prediction_implicit_false_belief + diana_prediction_false_belief_location + allie_predicition_false_belief_location)/3.0,
         fb_over_2 = as.integer((rachel_prediction_implicit_false_belief + diana_prediction_false_belief_location + allie_predicition_false_belief_location)>=2))
data$condition <- recode(data$condition, "VUI"="AI")
data$condition <- factor(data$condition, levels = c("Person", "AI"))
data$multiSSexperience <- factor(data$multiSSexperience)
```

## GLM
```{r data}
mod <- glm(chose_song_1  ~ 1 + condition * age * multiSSexperience, data=data, family = binomial)
summary(mod)

mod <- lm(tom  ~ age, data=data)
summary(mod)
person_data <- data %>%  filter(condition == "Person")
chisq.test(person_data$fb_over_2, person_data$chose_song_1)



summary(glm(chose_song_1  ~ fb_score, data=person_data, family = binomial))

mod2 <- glm(chose_song_1  ~ age * multiSSexperience, data=data %>% filter(condition=="AI"), family = binomial)
summary(mod2)
```

```{r, warning=FALSE, message = FALSE}
require(gridExtra)
theme_set(theme_classic())

colors <- c("Has Connected Smart Speakers" = "blue", "Without Connected Smart Speakers" = "red", "False Belief Score" = "black")


person_plot <- ggplot() +
    geom_smooth(data = data %>% filter(condition=="Person")  %>% filter(number_of_SS_in_home > 1), aes(x=age, y=chose_song_1), color="red") +
  geom_smooth(data = data %>% filter(condition=="Person")  %>% filter(number_of_SS_in_home <= 1), aes(x=age, y=chose_song_1), color="blue") +
  geom_smooth(data = data %>% filter(condition=="Person"), aes(x=age, y=fb_score), color="black") +
  coord_cartesian(ylim = c(0,1)) +
  labs(title = "Person Condition",
       x = "Age",
       y = "Accuracy",
       color = "") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"))

ai_plot <- ggplot() +
  geom_smooth(data = data %>% filter(condition=="AI")  %>% filter(number_of_SS_in_home > 1), aes(x=age, y=chose_song_1, color="Has Connected Smart Speakers")) +
  geom_smooth(data = data %>% filter(condition=="AI") %>% filter(number_of_SS_in_home <= 1), aes(x=age, y=chose_song_1, color="Without Connected Smart Speakers")) +
  geom_smooth(data = data %>% filter(condition=="AI"), aes(x=age, y=fb_score, color="False Belief Score")) +
  coord_cartesian(ylim = c(0,1)) +
  labs(title = "AI Condition",
       x = "Age",
       y = "",
       color = "") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "none",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold")) + 
  scale_color_manual(values = colors)

person_plot
ai_plot

grid.arrange(person_plot, ai_plot, ncol=2)
```

```{r recreation}
require(gridExtra)
binned_data <- data
binned_data$age_group <- cut(data$age,
                    breaks = c(3, 5, 7, Inf),
                    labels = c("3-4", "5-6", "7-8"),
                    right = FALSE)

bar_data <- binned_data %>% 
  group_by(age_group, condition) %>% 
  summarise(percent_song_1 = mean(chose_song_1),
            n = n())

key_plot <- ggplot(binned_data, aes(x=as.numeric(factor(age_group)), y=chose_song_1)) +
  geom_col(data=bar_data, aes(x=age_group, y=percent_song_1, fill=condition), position="Dodge", alpha=0.3) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), formula = y ~ x + I(x^2), aes(color=condition)) +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_fill_manual(values=c("#3D2785", "#999999")) +
  scale_color_manual(values=c("#3D2785", "#999999")) +
  labs(title = "Study Data",
       x = "Age",
       y = "Percent Consistent w/ Separate Minds",
       color = "Condition") +
  guides(color = guide_legend(order = 1), 
        linetype = guide_legend(order = 2),
        fill = "none") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "right",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))

key_plot
fb_bar_data <- binned_data %>% 
  group_by(age_group, condition) %>% 
  summarise(percent_fb_over_2 = mean(fb_over_2),
            n = n())

fb_plot <- ggplot(binned_data, aes(x=as.numeric(factor(age_group)), y=fb_over_2)) +
  geom_col(data=fb_bar_data, aes(x=age_group, y=percent_fb_over_2, fill=condition), position="Dodge", alpha=0.3) +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), formula = y ~ x, aes(color=condition)) +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.2,0.4,0.6,0.8,1)) +
  scale_fill_manual(values=c("#3D2785", "#999999")) +
  scale_color_manual(values=c("#3D2785", "#999999")) +
  labs(title = "False Belief Data",
       x = "Age",
       y = "Percent Above Chance on False Belief",
       color = "Condition") +
  guides(color = guide_legend(order = 1), 
        linetype = guide_legend(order = 2),
        fill = "none") +
  theme(plot.title = element_text(size = 18, color = "#595959", family = "Avenir Heavy"),
        text = element_text(size = 14, color = "#595959", family = "Avenir Medium"),
        axis.text = element_text(size = 12, color = "#595959", family = "Avenir Medium"),
        axis.ticks = element_line(color = "#595959"),
        axis.line.x = element_line(color = "#595959"),
        axis.line.y = element_line(color = "#595959"),
        legend.position = "none",
        legend.justification = "left",
        legend.text = element_text(size = 12),
        legend.title = element_text(face = "bold"))

grid.arrange(key_plot, fb_plot, ncol=2)
```
